/**
 * CWE Top 25 (2023) — Rule Pack
 *
 * Les 25 faiblesses logicielles les plus dangereuses selon le classement CWE/SANS 2023.
 * https://cwe.mitre.org/top25/archive/2023/2023_top25_list.html
 */

import type { Rule } from "../Rule.js";

export const cweTop25Rules: Rule[] = [
  {
    id: "CWE-787",
    name: "Out-of-bounds Write",
    description: "Écriture de données en dehors des limites d'un buffer ou d'une structure de données.",
    family: "sast",
    severity: "critical",
    cwe: "CWE-787",
    owasp: "A03:2021",
    enabled: true,
    tags: ["memory", "buffer-overflow", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/787.html"],
    remediation: "Valider les bornes de tous les accès aux buffers. Utiliser des langages/APIs sécurisés avec gestion de la mémoire.",
    confidence: 0.5,
    patterns: [],
  },
  {
    id: "CWE-79",
    name: "Cross-site Scripting (XSS)",
    description: "Données non validées reflétées ou stockées dans une page web, permettant l'exécution de scripts malveillants.",
    family: "sast",
    severity: "high",
    cwe: "CWE-79",
    owasp: "A03:2021",
    enabled: true,
    tags: ["injection", "xss", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/79.html"],
    remediation: "Encoder toutes les sorties. Utiliser une CSP stricte. Éviter innerHTML avec données dynamiques.",
    confidence: 0.8,
    patterns: [
      {
        regex: "innerHTML\\s*=\\s*[^'\"`]",
        regexFlags: "gm",
        extensions: [".ts", ".tsx", ".js", ".jsx"],
      },
      {
        regex: "document\\.write\\s*\\(",
        regexFlags: "gm",
        extensions: [".ts", ".js"],
      },
    ],
  },
  {
    id: "CWE-89",
    name: "SQL Injection",
    description: "Construction de requêtes SQL avec des données utilisateur non validées.",
    family: "sast",
    severity: "critical",
    cwe: "CWE-89",
    owasp: "A03:2021",
    enabled: true,
    tags: ["injection", "sql", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/89.html"],
    remediation: "Utiliser des requêtes paramétrées (prepared statements) ou un ORM sécurisé.",
    confidence: 0.85,
    patterns: [
      {
        regex: "(?:query|execute|run)\\s*\\([`'\"][^`'\"]*(?:SELECT|INSERT|UPDATE|DELETE)[^`'\"]*\\$\\{",
        regexFlags: "gim",
        extensions: [".ts", ".js"],
      },
    ],
  },
  {
    id: "CWE-416",
    name: "Use After Free",
    description: "Référence à une zone mémoire déjà libérée.",
    family: "sast",
    severity: "critical",
    cwe: "CWE-416",
    enabled: true,
    tags: ["memory", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/416.html"],
    remediation: "Initialiser les pointeurs à NULL après libération. Utiliser des smart pointers (C++) ou des langages avec GC.",
    confidence: 0.3,
    patterns: [],
  },
  {
    id: "CWE-78",
    name: "OS Command Injection",
    description: "Injection de commandes OS via des données utilisateur non validées.",
    family: "sast",
    severity: "critical",
    cwe: "CWE-78",
    owasp: "A03:2021",
    enabled: true,
    tags: ["injection", "command", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/78.html"],
    remediation: "Éviter exec/shell. Utiliser des listes blanches. Échapper les arguments via shellescape.",
    confidence: 0.85,
    patterns: [
      {
        regex: "(?:exec|execSync|spawn|spawnSync)\\s*\\([`'\"][^`'\"]*\\$\\{",
        regexFlags: "gim",
        extensions: [".ts", ".js"],
      },
    ],
  },
  {
    id: "CWE-20",
    name: "Improper Input Validation",
    description: "Absence de validation ou validation insuffisante des entrées utilisateur.",
    family: "sast",
    severity: "high",
    cwe: "CWE-20",
    owasp: "A03:2021",
    enabled: true,
    tags: ["validation", "input", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/20.html"],
    remediation: "Valider toutes les entrées (type, format, longueur, plage). Utiliser des schémas de validation (Zod, Joi, Yup).",
    confidence: 0.5,
    patterns: [
      {
        regex: "req\\.(?:body|query|params)\\.[a-zA-Z_]+(?!.*(?:validate|sanitize|parse|schema|zod|joi))",
        regexFlags: "gm",
        extensions: [".ts", ".js"],
      },
    ],
  },
  {
    id: "CWE-125",
    name: "Out-of-bounds Read",
    description: "Lecture de données en dehors des limites d'un buffer.",
    family: "sast",
    severity: "high",
    cwe: "CWE-125",
    enabled: true,
    tags: ["memory", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/125.html"],
    remediation: "Valider les indices avant accès. Utiliser des langages avec bornes automatiques.",
    confidence: 0.3,
    patterns: [],
  },
  {
    id: "CWE-22",
    name: "Path Traversal",
    description: "Utilisation de séquences '../' pour accéder à des fichiers hors du répertoire autorisé.",
    family: "sast",
    severity: "high",
    cwe: "CWE-22",
    owasp: "A01:2021",
    enabled: true,
    tags: ["path-traversal", "file", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/22.html"],
    remediation: "Normaliser les chemins avec path.resolve(). Vérifier que le chemin résolu est dans le répertoire autorisé.",
    confidence: 0.8,
    patterns: [
      {
        regex: "fs\\.(?:readFile|writeFile|readFileSync|writeFileSync|createReadStream)\\s*\\([^)]*(?:req\\.|request\\.|params\\.|query\\.|body\\.)",
        regexFlags: "gm",
        extensions: [".ts", ".js"],
      },
      {
        regex: "path\\.join\\s*\\([^)]*(?:req\\.|request\\.|params\\.)",
        regexFlags: "gm",
        extensions: [".ts", ".js"],
      },
    ],
  },
  {
    id: "CWE-352",
    name: "Cross-Site Request Forgery (CSRF)",
    description: "Absence de protection CSRF pour les requêtes mutantes (POST, PUT, DELETE).",
    family: "sast",
    severity: "high",
    cwe: "CWE-352",
    owasp: "A01:2021",
    enabled: true,
    tags: ["csrf", "web", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/352.html"],
    remediation: "Utiliser des tokens CSRF (synchronizer pattern) ou valider l'Origin/Referer.",
    confidence: 0.5,
    patterns: [],
  },
  {
    id: "CWE-434",
    name: "Unrestricted File Upload",
    description: "Téléversement de fichiers sans restriction de type ou de contenu.",
    family: "sast",
    severity: "high",
    cwe: "CWE-434",
    owasp: "A04:2021",
    enabled: true,
    tags: ["upload", "file", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/434.html"],
    remediation: "Valider le type MIME et l'extension. Scanner le contenu. Stocker hors du webroot.",
    confidence: 0.7,
    patterns: [
      {
        regex: "multer|formidable|busboy|multiparty",
        regexFlags: "gi",
        extensions: [".ts", ".js"],
      },
    ],
  },
  {
    id: "CWE-862",
    name: "Missing Authorization",
    description: "Absence de vérification des droits d'accès avant d'effectuer une action sensible.",
    family: "sast",
    severity: "critical",
    cwe: "CWE-862",
    owasp: "A01:2021",
    enabled: true,
    tags: ["authorization", "access-control", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/862.html"],
    remediation: "Implémenter un contrôle d'accès basé sur les rôles (RBAC). Vérifier les droits à chaque action.",
    confidence: 0.4,
    patterns: [],
  },
  {
    id: "CWE-476",
    name: "NULL Pointer Dereference",
    description: "Déréférencement d'un pointeur NULL, provoquant un crash.",
    family: "sast",
    severity: "medium",
    cwe: "CWE-476",
    enabled: true,
    tags: ["null-pointer", "crash", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/476.html"],
    remediation: "Vérifier la nullité avant déréférencement. Utiliser l'optional chaining (?.) en TypeScript/JavaScript.",
    confidence: 0.5,
    patterns: [],
  },
  {
    id: "CWE-502",
    name: "Deserialization of Untrusted Data",
    description: "Désérialisation de données non fiables pouvant mener à l'exécution de code arbitraire.",
    family: "sast",
    severity: "critical",
    cwe: "CWE-502",
    owasp: "A08:2021",
    enabled: true,
    tags: ["deserialization", "rce", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/502.html"],
    remediation: "Valider les données avant désérialisation. Utiliser JSON.parse() plutôt que eval(). Éviter les formats binaires non fiables.",
    confidence: 0.85,
    patterns: [
      {
        regex: "eval\\s*\\([^)]*(?:req\\.|request\\.|params\\.|query\\.|body\\.)",
        regexFlags: "gm",
        extensions: [".ts", ".js"],
      },
      {
        regex: "Function\\s*\\([^)]*(?:req\\.|request\\.|params\\.)",
        regexFlags: "gm",
        extensions: [".ts", ".js"],
      },
      {
        regex: "yaml\\.load\\s*\\(",
        regexFlags: "gm",
        extensions: [".ts", ".js"],
      },
      {
        regex: "pickle\\.loads\\s*\\(",
        regexFlags: "gm",
        extensions: [".py"],
      },
    ],
  },
  {
    id: "CWE-287",
    name: "Improper Authentication",
    description: "Authentification incorrecte ou contournable.",
    family: "sast",
    severity: "critical",
    cwe: "CWE-287",
    owasp: "A07:2021",
    enabled: true,
    tags: ["authentication", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/287.html"],
    remediation: "Utiliser des mécanismes d'authentification éprouvés. Implémenter MFA. Vérifier côté serveur.",
    confidence: 0.4,
    patterns: [],
  },
  {
    id: "CWE-190",
    name: "Integer Overflow or Wraparound",
    description: "Débordement d'entier conduisant à des comportements inattendus.",
    family: "sast",
    severity: "medium",
    cwe: "CWE-190",
    enabled: true,
    tags: ["integer-overflow", "arithmetic", "cwe-top25"],
    references: ["https://cwe.mitre.org/data/definitions/190.html"],
    remediation: "Valider les plages numériques. Utiliser des bibliothèques arithmétiques sécurisées pour les calculs critiques.",
    confidence: 0.3,
    patterns: [],
  },
];
